# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
steer1:
  ID: 21
  Operating_Mode: 4
  Return_Delay_Time: 0
  Direction: 1
  Homing_Offset: 12
steer2:
  ID: 22
  Operating_Mode: 4
  Return_Delay_Time: 0
  Direction: 0
  Homing_Offset: 0
steer3:
  ID: 23
  Operating_Mode: 4
  Return_Delay_Time: 0
  Direction: 0
  Homing_Offset: -140
steer4:
  ID: 24
  Operating_Mode: 4
  Return_Delay_Time: 0
  Direction: 0
  Homing_Offset: 0

